owner: lincgit
repo: uptime-monitor

sites:
  - name: linc.nl
    url: https://linc.nl/

status-website:
theme: night
  metaTags:
    - name: "robots"
      content: "noindex, nofollow"
  name: LiNC Uptime Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  cname: status.linc.nl
  introTitle: "**LiNC Uptime Monitor**"
