owner: lincgit
repo: linc-uptime-monitor
sites:
   - name: adhulst.nl
     url: https://adhulst.nl
   - name: alltape.eu
     url: https://alltape.eu
   - name: barrelandboar.nl
     url: https://barrelandboar.nl
   - name: bedding-concepts.nl
     url: https://bedding-concepts.nl
   - name: bioammo.nl
     url: https://bioammo.nl
   - name: bisley.nl
     url: https://bisley.nl
   - name: boardingfestival.com
     url: https://boardingfestival.com
   - name: cafeaula.nl
     url: https://cafeaula.nl
   - name: charterama.com
     url: https://charterama.com
   - name: con-questa.com
     url: https://con-questa.com
   - name: creativefamily.nl
     url: https://creativefamily.nl
   - name: defender-boxes.com
     url: https://defender-boxes.com
   - name: dehorstgoes.nl
     url: https://dehorstgoes.nl
   - name: deprovinciekiest.nl
     url: https://deprovinciekiest.nl
   - name: deschakelgoes.nl
     url: https://deschakelgoes.nl
   - name: detail4retail.nl
     url: https://detail4retail.nl
   - name: easypiezie.nl
     url: https://easypiezie.nl
   - name: enlarg3d.nl
     url: https://enlarg3d.nl
   - name: etagon.nl
     url: https://etagon.nl
   - name: faes-packaging-solutions.com
     url: https://faes-packaging-solutions.com
   - name: fuchs-wse.nl
     url: https://fuchs-wse.nl
   - name: getaheadineurope.com
     url: https://getaheadineurope.com
   - name: glatzonline.nl
     url: https://glatzonline.nl
   - name: gocompany.nl
     url: https://gocompany.nl
   - name: greeniuz.nl
     url: https://greeniuz.nl
   - name: hollandpackaging.nl
     url: https://hollandpackaging.nl
   - name: hydratechbenelux.nl
     url: https://hydratechbenelux.nl
   - name: ikswitch.nu
     url: https://ikswitch.nu
   - name: infocvb.nl
     url: https://infocvb.nl
   - name: inglasco-int.com
     url: https://inglasco-int.com
   - name: inglasco.nl
     url: https://inglasco.nl
   - name: innoseal.shop
     url: https://innoseal.shop
   - name: intranet.wspmiddenbrabant.nl
     url: https://intranet.wspmiddenbrabant.nl
   - name: jcmeijers.com
     url: https://jcmeijers.com
   - name: kootstrarijopleidingen.nl
     url: https://kootstrarijopleidingen.nl
   - name: kristelsfashion.nl
     url: https://kristelsfashion.nl
   - name: lan-intranet.nl
     url: https://lan-intranet.nl
   - name: lanhandling.com
     url: https://lanhandling.com
   - name: lekker-brabant.nl
     url: https://lekker-brabant.nl
   - name: libretica.nl
     url: https://libretica.nl
   - name: linc.nl
     url: https://linc.nl
   - name: magna-capital-partners.com
     url: https://magna-capital-partners.com
   - name: marcom-inhouse.nl
     url: https://marcom-inhouse.nl
   - name: marquardt-kuchen.nl
     url: https://marquardt-kuchen.nl
   - name: mensgerichteouderenzorg.nl
     url: https://mensgerichteouderenzorg.nl
   - name: mondzorgbaliendijk.nl
     url: https://mondzorgbaliendijk.nl
   - name: move.scheepens.nl
     url: https://move.scheepens.nl
   - name: newbridges.nl
     url: https://newbridges.nl
   - name: nextadvocaten.nl
     url: https://nextadvocaten.nl
   - name: nvp-unima.nl
     url: https://nvp-unima.nl
   - name: olympushillegersberg.nl
     url: https://olympushillegersberg.nl
   - name: outings.nl
     url: https://outings.nl
   - name: pontex-ip.nl
     url: https://pontex-ip.nl
   - name: skb-europe.com
     url: https://skb-europe.com
   - name: specialolympics2024.nl
     url: https://specialolympics2024.nl
   - name: studio-tegenlicht.nl
     url: https://studio-tegenlicht.nl
   - name: swinhovegroep.nl
     url: https://swinhovegroep.nl
   - name: thepostoffice013.nl
     url: https://thepostoffice013.nl
   - name: vandaagvoorlater.nl
     url: https://vandaagvoorlater.nl
   - name: vdsprojects.nl
     url: https://vdsprojects.nl
   - name: vekon.nl
     url: https://vekon.nl
   - name: vhex.nl
     url: https://vhex.nl
   - name: viking-boxes.com
     url: https://viking-boxes.com
   - name: vivar.nl
     url: https://vivar.nl
   - name: vivarforwarding.nl
     url: https://vivarforwarding.nl
   - name: vn-plu.com
     url: https://vn-plu.com
   - name: werkenbij.vlc-partners.nl
     url: https://werkenbij.vlc-partners.nl
   - name: werkenbijswinhove.nl
     url: https://werkenbijswinhove.nl
   - name: win-rs.nl
     url: https://win-rs.nl
   - name: wolterwolthers.nl
     url: https://wolterwolthers.nl
   - name: wonenbijdefamilie.nl
     url: https://wonenbijdefamilie.nl
   - name: wsphelmond-depeel.nl
     url: https://wsphelmond-depeel.nl
   - name: yourvolvo.nl
     url: https://yourvolvo.nl
status-website:
   name: Uptime Monitor
   cname: status.linc.nl
   robotsText: "User-agent: * \n Disallow: /"
   logoUrl: https://raw.githubusercontent.com/lincgit/linc-uptime-monitor/master/assets/logo.svg
   faviconSvg: https://raw.githubusercontent.com/lincgit/linc-uptime-monitor/master/assets/favicon.svg
   theme: night
i18n:
   footer: LiNC
