owner: lincgit
repo: uptime-monitor

sites:
  - name: linc.nl
    url: https://linc.nl/

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  theme: night
  logoUrl: https://raw.githubusercontent.com/lincgit/uptime-monitor/master/assets/logo.svg
  faviconSvg: https://raw.githubusercontent.com/lincgit/uptime-monitor/master/assets/favicon.svg
  cname: status.linc.nl
 
i18n:
  footer: LiNC
